---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
    theme: united
editor_options:
  chunk_output_type: console
---

This R tutorial provides a comprehensive guide to various R programming techniques and data science methods.

### **Module 1:** Introduction

***Basics:***

-   Introduces the RStudio interface, basic R operations, functions, package installation, data importing, indexing, and essential data manipulation skills.

***Data Preprocessing:***

-   Covers key steps like data collection, cleaning, transformation, and reduction to prepare datasets for analysis.

***Visualisation:***

-   Demonstrates how to create scatter plots, box plots, heatmaps, survival plots, and pie charts for effective data visualization.

### **Module 2:** Machine Learning

***Supervised Learning:***

-   Explains regression, classification, cross-validation, and feature transformation techniques for predictive modeling.

***Unsupervised Learning:***

-   Explores clustering methods, including K-means, hierarchical, probabilistic, and DBSCAN, for identifying patterns in data without labels.

### **miRseq Analysis Tutorial:**

Using what we have learnt from this tutorial we present an example analysis one could perform from a biological perspective. In this case study we investigate the differences in gene expression within a Colerectal Adenocarcinoma cohort.

Gene expression of four genes (`LCN2`, `CXCL3`, `GPX2`, & `CXCL2`) were analysed within primary Colerectal Adenocarcinoma tissue samples from patients (`01A`).
